### PR TITLE
Delete Logout (1).svg

### PR DESCRIPTION
**Pull request by dingdingxia**
Comment Test

1. point 1
2. point 2
Summary

### CODE REVIEW

**Comment by dingdingxia** [comment]
> comment test
>
> 1. point 1
> 2. point 2
> Summary

Why so complex?

**Comment by dingdingxia** [comment]
> > comentttttttt
> > 
> > 1. 32535
> > 2. ettt
> > 
> > 
> > * [ ]
> 
> what? quote comment



> comentttttttt
> 
> 1. 32535
> 2. ettt
> 
> * [ ]



> Comment Test
> 
> 1. point 1
Agree
> 2. point 2
I don't agree.
>    Summary
Sure!

**Comment by OliviaCai214** [comment]
> Comment Test
> 
> 1. point 1
But what about this?

> 2. point 2
>    Summary

I don't understand.

**Comment by OliviaCai214** [comment]
> Comment Test
> 
> 1. point 1
But what about this?

> 2. point 2
>    Summary

I don't understand.

**Pull request merged**
